version: 0.1
log:
  fields:
    service: registry
storage:
  delete:
    enabled: true
  cache:
    blobdescriptor: inmemory

http:
  addr: 0.0.0.0:5000

auth:
  htpasswd:
    realm: basic-realm
    path: /auth/htpasswd