version: "3"

services:
  registry:
    restart: always
    image: registry:2

    environment:
        REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./registry/data:/data
      - ./registry/config.yml:/etc/docker/registry/config.yml

    labels:
      - "traefik.http.routers.registry.rule=Host(`${APP_ADDRESS}`) && PathPrefix(`/v2/{*}`)"

  # Source: https://github.com/Joxit/docker-registry-ui
  registry-ui:
    restart: always
    image: joxit/docker-registry-ui:2
    environment:
        REGISTRY_TITLE: "My Registry"
        REGISTRY_NAME: "My Registry"
        REGISTRY_SSL: "false"
    depends_on:
        - registry
    labels:
      - "traefik.http.routers.registry-ui.rule=Host(`${APP_ADDRESS}`)"
      - "traefik.http.routers.registry-ui.entrypoints=websecure"
      - "traefik.http.routers.registry-ui.tls.certresolver=le"

  reverse-proxy:
    restart: always
    image: traefik:2.9
    command:
      - --log.level=DEBUG
      - --providers.docker=true
      - --api.insecure=true
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --certificatesresolvers.le.acme.email=${EMAIL}
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory

    ports:
        - "443:443"
        - "8080:8080"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ./traefik/letsencrypt:/letsencrypt